#!/usr/bin/env ruby

require 'pp'

module Fehu; end

require_relative 'lib/parser'
require_relative 'lib/ast/node'
require_relative 'lib/ast/int'
require_relative 'lib/ast/float'
require_relative 'lib/ast/string'
require_relative 'lib/ast/atom'
require_relative 'lib/ast/tag'
require_relative 'lib/ast/call'
require_relative 'lib/ast/case'
require_relative 'lib/ast/lambda'
require_relative 'lib/ast/bind'
require_relative 'lib/ast/blank'

require_relative 'lib/std/extensions'

def ast(script)
  parser = Fehu::Parser.new(script + "\n")
  if parser.parse
    parser.ast.last.map(&:rewrite)
  else
    raise parser.failure_info
  end
end

if ARGV[0] == '-ast'
  pp ast(File.read ARGV[1])
else
  script = File.read(ARGV[0])
  env = {}
  ast(script).each{|node| node.run(env) }
end
