#!/usr/bin/env ruby

require 'pp'

module Fehu; end

require_relative 'lib/parser'
require_relative 'lib/ast/int'
require_relative 'lib/ast/float'
require_relative 'lib/ast/string'
require_relative 'lib/ast/atom'
require_relative 'lib/ast/tag'
require_relative 'lib/ast/call'
require_relative 'lib/ast/lambda'

if ARGV[0] == '-ast'
  script = File.read(ARGV[1])
  parser = Fehu::Parser.new(script + "\n")
  if parser.parse
    pp parser.ast
  else
    pp parser.failure_info
  end
else
  script = File.read(ARGV[0])
  parser = Fehu::Parser.new(script + "\n")

  if parser.parse
    pp Fehu::Evaluator.new.run(parser.ast)
  else
    pp parser.failure_info
  end
end
